# Snowflake-native dbt profile
# Authentication is handled by Snowflake - no password/authenticator needed
snowflake_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{your_snowflake_account}"
      user: "{your_user}"
      role: ACCOUNTADMIN
      database: RETAIL_BANKING_DB
      warehouse: DATA_PRODUCTS_WH
      schema: DATA_PRODUCTS
      threads: 4
