# ============================================================================
# DATA PRODUCT CANVAS: Retail Customer Churn Risk
# ============================================================================
# This canvas captures the business intent, stakeholders, and success measures
# for the data product BEFORE diving into technical design.
# 
# Purpose: Align business, risk, compliance, and technology teams on WHAT
# problem we're solving and WHO benefits from this data product.
# ============================================================================

apiVersion: v1
kind: DataProductCanvas
metadata:
  name: retail-customer-churn-risk
  version: "1.0.0"
  created_date: "2024-01-15"
  last_updated: "2024-01-15"
  status: discovery

# ============================================================================
# SECTION 1: BUSINESS TRIGGER
# What event or observation initiated this data product?
# ============================================================================
business_trigger:
  event: "Rising churn in retail current accounts"
  observation: |
    Q3 analysis revealed a 15% increase in current account closures among 
    retail customers aged 25-40. Exit surveys indicate competitors offering 
    better digital experiences and personalized services.
  urgency: high
  estimated_impact:
    annual_revenue_at_risk: "NZD $12M"
    customer_lifetime_value_impact: "2,400 customers at high risk"

# ============================================================================
# SECTION 2: PROBLEM STATEMENT
# What specific problem does this data product solve?
# ============================================================================
problem_statement:
  description: |
    The Retail Banking division lacks a unified, trusted view of customer 
    churn risk. Currently:
    - Risk team uses quarterly batch reports from core banking
    - Marketing relies on campaign response data in Salesforce
    - Digital team tracks app engagement separately
    - Branch managers use spreadsheets with local knowledge
    
    This fragmentation means:
    - High-risk customers are identified too late for intervention
    - Retention campaigns target the wrong segments
    - No ability to explain or defend churn predictions to regulators
  
  root_causes:
    - "Multiple versions of customer data across teams"
    - "No real-time signals from digital channels"
    - "Inconsistent definition of 'at-risk' customer"
    - "Manual, spreadsheet-based risk scoring"

# ============================================================================
# SECTION 3: TARGET USERS & STAKEHOLDERS
# Who will consume this data product?
# ============================================================================
stakeholders:
  data_product_owner:
    name: "Sarah Mitchell"
    role: "Head of Retail Customer Analytics"
    department: "Retail Banking"
    email: "sarah.mitchell@bank.com"
  
  multi_disciplinary_team:
    - role: "Domain SME - Risk"
      name: "James Chen"
      department: "Retail Credit Risk"
      responsibility: "Define risk factors and thresholds"
    
    - role: "Domain SME - Operations"
      name: "Priya Sharma"
      department: "Branch Operations"
      responsibility: "Validate against operational reality"
    
    - role: "Data Engineer"
      name: "Marcus Williams"
      department: "Data Platform Team"
      responsibility: "Build and maintain pipelines on Snowflake"
    
    - role: "Compliance Officer"
      name: "Emma Thompson"
      department: "Regulatory Compliance"
      responsibility: "Ensure explainability and audit trail"
    
    - role: "Platform Security"
      name: "David Park"
      department: "Information Security"
      responsibility: "Access controls and data classification"

  target_consumers:
    - name: "Retention Analytics Team"
      use_case: "Identify customers for proactive retention campaigns"
      access_level: "Full PII access"
      frequency: "Daily"
    
    - name: "Branch Relationship Managers"
      use_case: "Prioritize customer outreach"
      access_level: "Masked PII (name visible, contact details hidden)"
      frequency: "Weekly dashboard"
    
    - name: "Marketing Campaign Team"
      use_case: "Target retention offers"
      access_level: "Aggregated segments only"
      frequency: "Monthly"
    
    - name: "Executive Leadership"
      use_case: "Track churn KPIs and intervention effectiveness"
      access_level: "Aggregated metrics only"
      frequency: "Monthly board report"

# ============================================================================
# SECTION 4: KEY PERFORMANCE INDICATORS (KPIs)
# How will we measure success?
# ============================================================================
kpis:
  primary:
    - name: "Churn Rate Reduction"
      baseline: "8.5% quarterly churn"
      target: "6.0% quarterly churn"
      measurement: "Percentage of retail customers closing all accounts"
      timeframe: "Within 12 months of product launch"
    
    - name: "Early Warning Accuracy"
      baseline: "N/A (no current model)"
      target: "75% precision at 30-day horizon"
      measurement: "Customers flagged as high-risk who actually churned"
      timeframe: "Within 6 months"

  secondary:
    - name: "Retention Campaign Uplift"
      target: "20% improvement in campaign response rate"
      measurement: "Response rate for campaigns using churn scores vs. control"
    
    - name: "Time to Intervention"
      baseline: "45 days average"
      target: "7 days average"
      measurement: "Days from risk signal to first customer contact"
    
    - name: "Data Product Adoption"
      target: "80% of retention decisions use churn score"
      measurement: "Survey of retention team + system usage logs"

  guardrails:
    - name: "False Positive Rate"
      threshold: "< 30%"
      description: "Avoid over-contacting satisfied customers"
    
    - name: "Regulatory Explainability"
      threshold: "100% of predictions have documented factors"
      description: "Every score must be explainable for FCA review"

# ============================================================================
# SECTION 5: CANDIDATE DATA SOURCES
# What data do we need to build this product?
# ============================================================================
candidate_data_sources:
  - source_name: "Core Banking System"
    system: "Temenos T24"
    data_elements:
      - "Customer demographics"
      - "Account balances and types"
      - "Transaction history"
      - "Product holdings"
      - "Tenure and relationship age"
    refresh_frequency: "Daily batch (T+1)"
    data_quality: "High - system of record"
    owner: "Core Banking Operations"
  
  - source_name: "CRM System"
    system: "Salesforce Financial Services Cloud"
    data_elements:
      - "Customer interactions"
      - "Complaint history"
      - "Service requests"
      - "Relationship manager notes"
    refresh_frequency: "Near real-time"
    data_quality: "Medium - depends on manual entry"
    owner: "Customer Experience Team"
  
  - source_name: "Digital Channels"
    system: "Mobile App Analytics (Amplitude)"
    data_elements:
      - "App login frequency"
      - "Feature usage patterns"
      - "Session duration"
      - "Last active date"
    refresh_frequency: "Real-time streaming"
    data_quality: "High - automated capture"
    owner: "Digital Banking Team"
  
  - source_name: "Complaints Management"
    system: "ServiceNow"
    data_elements:
      - "Complaint category"
      - "Resolution status"
      - "Escalation history"
      - "Customer sentiment"
    refresh_frequency: "Daily"
    data_quality: "High - regulatory requirement"
    owner: "Customer Complaints Team"

# ============================================================================
# SECTION 6: DATA PRODUCT SCOPE
# What will this data product expose?
# ============================================================================
product_scope:
  name: "Retail Customer Churn Risk"
  description: |
    A governed, daily-refreshed data product that provides a unified view of 
    churn risk for retail banking customers. Combines behavioral signals, 
    transactional patterns, and engagement data to produce an explainable 
    risk score.
  
  key_entities:
    - entity: "Customer"
      grain: "One row per retail customer"
      key: "customer_id"
    
  key_attributes:
    - "churn_risk_score (0-100)"
    - "risk_tier (High/Medium/Low)"
    - "primary_risk_drivers (top 3 factors)"
    - "days_to_predicted_churn"
    - "recommended_intervention"
  
  refresh_frequency: "Daily by 6 AM UTC"
  
  historical_depth: "24 months rolling"
  
  exclusions:
    - "Business/Corporate customers (separate product)"
    - "Customers with < 30 days tenure (insufficient data)"
    - "Deceased or fraud-flagged accounts"

# ============================================================================
# SECTION 7: RISKS & DEPENDENCIES
# What could block or derail this data product?
# ============================================================================
risks:
  - risk: "Digital channel data quality varies by platform"
    likelihood: medium
    impact: high
    mitigation: "Implement data quality checks; fallback to core banking signals"
  
  - risk: "Compliance review may require model explainability changes"
    likelihood: medium
    impact: medium
    mitigation: "Engage compliance early; use interpretable model techniques"
  
  - risk: "Branch managers may not trust automated scores"
    likelihood: high
    impact: medium
    mitigation: "Include local context; provide score explanations; pilot program"

dependencies:
  - dependency: "Core Banking daily extract pipeline"
    owner: "Data Platform Team"
    status: "Existing - operational"
  
  - dependency: "Digital analytics data landing zone"
    owner: "Digital Banking Team"
    status: "In progress - ETA 4 weeks"
  
  - dependency: "Snowflake compute capacity"
    owner: "Cloud Infrastructure"
    status: "Approved - provisioning"

# ============================================================================
# SECTION 8: SUCCESS CRITERIA FOR DISCOVERY PHASE
# When is Discovery complete?
# ============================================================================
discovery_exit_criteria:
  - criteria: "All stakeholders have reviewed and signed off on this canvas"
    status: pending
  
  - criteria: "Data source access confirmed for all candidate sources"
    status: pending
  
  - criteria: "Initial data profiling complete (volume, quality, gaps)"
    status: pending
  
  - criteria: "Compliance has approved the data classification approach"
    status: pending
  
  - criteria: "Budget and timeline approved for Design phase"
    status: pending

# ============================================================================
# NEXT STEP: Once Discovery is complete, proceed to DESIGN phase
# to create the formal Data Contract
# ============================================================================

