version: 2

# =============================================================================
# SOURCES
# =============================================================================
sources:
  - name: raw
    database: RETAIL_BANKING_DB
    schema: RAW
    description: Raw source data from operational systems
    tables:
      - name: customers
        description: Core customer demographics and profile from Core Banking (T24)
        columns:
          - name: customer_id
            description: Primary key
            data_tests:
              - unique
              - not_null
      
      - name: accounts
        description: Customer accounts and products from Core Banking (T24)
        columns:
          - name: account_id
            description: Primary key
            data_tests:
              - unique
              - not_null
      
      - name: transactions
        description: Account transaction history
        columns:
          - name: txn_id
            description: Primary key
            data_tests:
              - unique
              - not_null
      
      - name: digital_engagement
        description: Mobile app and online banking activity from Digital (Amplitude)
        columns:
          - name: customer_id
            description: Foreign key to customers
            data_tests:
              - not_null
      
      - name: complaints
        description: Customer complaints and service issues from ServiceNow
        columns:
          - name: complaint_id
            description: Primary key
            data_tests:
              - unique
              - not_null

# =============================================================================
# MODELS
# =============================================================================
models:
  - name: retail_customer_churn_risk
    description: |
      Retail Customer Churn Risk data product.
      
      A governed, daily-refreshed data product providing unified churn risk 
      scores for retail banking customers. Combines behavioral signals, 
      transactional patterns, and engagement data to produce explainable 
      risk scores that power retention campaigns and branch interventions.
      
      Business Goal: Reduce customer churn from 8.5% to 6.0%
    
    meta:
      owner: Alex Morgan
      contact: alex.morgan@bank.com
      contract_version: '1.0.0'
      sla_freshness_hours: 24
      classification: confidential
    
    config:
      tags: ['churn', 'risk', 'retention', 'customer-analytics', 'PO123']
    
    columns:
      # Customer Identifiers
      - name: customer_id
        description: Unique identifier for the retail customer
        data_tests:
          - unique
          - not_null

      - name: customer_name
        description: Full name of the customer
        data_tests:
          - not_null
        meta:
          pii: true
          masking_policy: CUSTOMER_NAME_MASK

      - name: customer_segment
        description: Customer segment classification
        data_tests:
          - not_null
          - accepted_values:
              values: ['MASS_MARKET', 'MASS_AFFLUENT', 'AFFLUENT', 'HIGH_NET_WORTH']

      - name: region
        description: Geographic region of the customer

      # Relationship Attributes
      - name: relationship_tenure_months
        description: Number of months since customer onboarding
        data_tests:
          - not_null

      - name: total_products_held
        description: Count of active products held by customer

      - name: primary_account_balance
        description: Balance of primary current account

      - name: total_relationship_balance
        description: Sum of all account balances

      # Behavioral Signals
      - name: avg_monthly_transactions_3m
        description: Average monthly transaction count over last 3 months

      - name: transaction_trend
        description: Transaction volume trend direction
        data_tests:
          - accepted_values:
              values: ['INCREASING', 'STABLE', 'DECLINING', 'SEVERELY_DECLINING']

      - name: balance_trend
        description: Account balance trend direction
        data_tests:
          - accepted_values:
              values: ['INCREASING', 'STABLE', 'DECLINING', 'SEVERELY_DECLINING']

      - name: days_since_last_transaction
        description: Days since the last account transaction

      # Digital Engagement Signals
      - name: mobile_app_active
        description: Whether customer has used mobile app in last 30 days

      - name: login_count_30d
        description: Number of digital banking logins in last 30 days

      - name: digital_engagement_score
        description: Composite digital engagement score (0-100)

      # Complaint Signals
      - name: open_complaints_count
        description: Number of currently open complaints

      - name: complaints_last_12m
        description: Total complaints filed in last 12 months

      - name: has_unresolved_complaint
        description: Flag indicating unresolved complaint exists

      # Risk Driver Flags
      - name: declining_balance_flag
        description: Significant balance decline detected

      - name: reduced_activity_flag
        description: Reduced transaction activity detected

      - name: low_engagement_flag
        description: Low digital engagement detected

      - name: complaint_flag
        description: Recent or unresolved complaint exists

      - name: dormancy_flag
        description: Account showing dormancy signals

      # Churn Risk Outputs
      - name: churn_risk_score
        description: Calculated churn risk score (0-100, higher = more risk)
        data_tests:
          - not_null

      - name: risk_tier
        description: Risk categorization based on score thresholds
        data_tests:
          - not_null
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']

      - name: primary_risk_driver
        description: The most significant factor contributing to churn risk
        data_tests:
          - not_null
          - accepted_values:
              values: ['BALANCE_DECLINE', 'ACTIVITY_REDUCTION', 'LOW_ENGAGEMENT', 
                       'COMPLAINTS', 'DORMANCY', 'MULTI_FACTOR', 'NONE']

      - name: risk_drivers_json
        description: JSON object of all contributing risk factors with details

      # Recommended Actions
      - name: recommended_intervention
        description: Suggested retention intervention based on risk profile
        data_tests:
          - not_null
          - accepted_values:
              values: ['NO_ACTION', 'DIGITAL_ENGAGEMENT', 'RELATIONSHIP_CALL', 
                       'BRANCH_MEETING', 'RETENTION_OFFER', 'URGENT_ESCALATION']

      - name: intervention_priority
        description: Priority ranking for intervention (1=highest)

      # Metadata & Audit
      - name: score_calculated_at
        description: Timestamp when churn score was calculated
        data_tests:
          - not_null

      - name: data_as_of_date
        description: Business date of the source data
        data_tests:
          - not_null

      - name: model_version
        description: Version of the churn risk model used
        data_tests:
          - not_null
