-- ============================================================================
-- DBT MODEL: Retail Customer Churn Risk
-- ============================================================================
-- Generated by: dbt Code Generator (03b_dbt_generator_app.py)
-- Source: Data Contract (02_design/churn_risk_data_contract.yaml)
-- 
-- This model was generated from English derivation definitions in the contract
-- using Snowflake Cortex LLM. Validated and tested against sample data.
-- ============================================================================

{{
  config(
    materialized='table',
    unique_key='customer_id'
  )
}}

WITH customers AS (
  SELECT 
    customer_id,
    customer_name,
    customer_segment,
    region,
    onboarding_date
  FROM {{ source('raw', 'customers') }}
  WHERE kyc_status = 'VERIFIED'
),

accounts AS (
  SELECT 
    customer_id,
    account_id,
    account_type,
    current_balance
  FROM {{ source('raw', 'accounts') }}
  WHERE account_status = 'ACTIVE'
),

transactions_last_6m AS (
  SELECT 
    t.account_id,
    t.txn_date,
    t.txn_id,
    t.amount,
    a.customer_id
  FROM {{ source('raw', 'transactions') }} t
  JOIN accounts a ON t.account_id = a.account_id
  WHERE txn_date >= DATEADD(month, -6, CURRENT_DATE())
),

digital_engagement AS (
  SELECT 
    customer_id,
    login_count_30d,
    mobile_app_active,
    features_used_count
  FROM {{ source('raw', 'digital_engagement') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY measurement_date DESC) = 1
),

complaints AS (
  SELECT 
    customer_id,
    complaint_id,
    status,
    severity
  FROM {{ source('raw', 'complaints') }}
  WHERE complaint_date >= DATEADD(month, -12, CURRENT_DATE())
),

customer_metrics AS (
  SELECT
    c.customer_id,
    c.customer_name,
    c.customer_segment,
    c.region,
    DATEDIFF(month, c.onboarding_date, CURRENT_DATE()) as relationship_tenure_months,
    COUNT(DISTINCT a.account_id) as total_products_held,
    MAX(CASE WHEN a.account_type = 'CURRENT_ACCOUNT' THEN a.current_balance ELSE 0 END) as primary_account_balance,
    SUM(a.current_balance) as total_relationship_balance,
    COUNT(DISTINCT CASE WHEN t.txn_date >= DATEADD(month, -3, CURRENT_DATE()) THEN t.txn_id END)/3 as avg_monthly_transactions_3m,
    DATEDIFF(day, MAX(t.txn_date), CURRENT_DATE()) as days_since_last_transaction
  FROM customers c
  LEFT JOIN accounts a ON c.customer_id = a.customer_id
  LEFT JOIN transactions_last_6m t ON a.account_id = t.account_id
  GROUP BY 1,2,3,4,5
),

transaction_trends AS (
  SELECT 
    customer_id,
    COUNT(CASE WHEN txn_date >= DATEADD(month, -3, CURRENT_DATE()) THEN 1 END) as recent_txns,
    COUNT(CASE WHEN txn_date BETWEEN DATEADD(month, -6, CURRENT_DATE()) AND DATEADD(month, -3, CURRENT_DATE()) THEN 1 END) as prior_txns,
    CASE
      WHEN recent_txns > prior_txns * 1.1 THEN 'INCREASING'
      WHEN recent_txns BETWEEN prior_txns * 0.9 AND prior_txns * 1.1 THEN 'STABLE'
      WHEN recent_txns BETWEEN prior_txns * 0.5 AND prior_txns * 0.9 THEN 'DECLINING'
      WHEN recent_txns < prior_txns * 0.5 THEN 'SEVERELY_DECLINING'
      ELSE 'STABLE'
    END as transaction_trend
  FROM transactions_last_6m
  GROUP BY customer_id
),

complaint_metrics AS (
  SELECT
    customer_id,
    COUNT(CASE WHEN status = 'OPEN' THEN 1 END) as open_complaints_count,
    COUNT(*) as complaints_last_12m
  FROM complaints
  GROUP BY customer_id
),

risk_flags AS (
  SELECT
    m.*,
    t.transaction_trend,
    d.login_count_30d,
    d.mobile_app_active,
    d.features_used_count,
    cm.open_complaints_count,
    cm.complaints_last_12m,
    CASE WHEN total_relationship_balance > 1000 THEN 'STABLE' ELSE 'DECLINING' END as balance_trend,
    
    -- Digital engagement score
    LEAST(100, 
      COALESCE(d.login_count_30d, 0) * 2 +
      CASE WHEN d.mobile_app_active THEN 20 ELSE 0 END +
      COALESCE(d.features_used_count, 0) * 2
    ) as digital_engagement_score,
    
    -- Risk flags
    (total_relationship_balance < 500 OR primary_account_balance < 100) as declining_balance_flag,
    (t.recent_txns < t.prior_txns * 0.7) as reduced_activity_flag,
    (COALESCE(d.login_count_30d, 0) < 3 AND COALESCE(d.mobile_app_active, false) = false) as low_engagement_flag,
    (COALESCE(cm.open_complaints_count, 0) > 0 OR COALESCE(cm.complaints_last_12m, 0) >= 2) as complaint_flag,
    (days_since_last_transaction > 45) as dormancy_flag
  FROM customer_metrics m
  LEFT JOIN transaction_trends t ON m.customer_id = t.customer_id
  LEFT JOIN digital_engagement d ON m.customer_id = d.customer_id
  LEFT JOIN complaint_metrics cm ON m.customer_id = cm.customer_id
),

final AS (
  SELECT
    customer_id,
    customer_name,
    customer_segment,
    region,
    relationship_tenure_months,
    total_products_held,
    primary_account_balance,
    total_relationship_balance,
    avg_monthly_transactions_3m,
    transaction_trend,
    balance_trend,
    days_since_last_transaction,
    mobile_app_active,
    login_count_30d,
    digital_engagement_score,
    open_complaints_count,
    complaints_last_12m,
    open_complaints_count > 0 as has_unresolved_complaint,
    
    -- Calculate churn risk score
    LEAST(100, GREATEST(0,
      20 + -- Base score
      CASE WHEN declining_balance_flag THEN 20 ELSE 0 END +
      CASE WHEN reduced_activity_flag THEN 20 ELSE 0 END +
      CASE WHEN low_engagement_flag THEN 15 ELSE 0 END +
      CASE WHEN complaint_flag THEN 15 ELSE 0 END +
      CASE WHEN dormancy_flag THEN 25 ELSE 0 END -
      CASE WHEN total_products_held >= 3 THEN 10 ELSE 0 END -
      CASE WHEN relationship_tenure_months > 60 THEN 10 ELSE 0 END -
      CASE WHEN digital_engagement_score > 70 THEN 10 ELSE 0 END +
      CASE WHEN customer_segment = 'MASS_MARKET' THEN 5
           WHEN customer_segment = 'HIGH_NET_WORTH' THEN -5
           ELSE 0 END
    )) as churn_risk_score,
    
    -- Derive risk tier
    CASE 
      WHEN churn_risk_score <= 25 THEN 'LOW'
      WHEN churn_risk_score <= 50 THEN 'MEDIUM'
      WHEN churn_risk_score <= 75 THEN 'HIGH'
      ELSE 'CRITICAL'
    END as risk_tier,
    
    declining_balance_flag,
    reduced_activity_flag,
    low_engagement_flag,
    complaint_flag,
    dormancy_flag,
    
    -- Determine primary risk driver
    CASE
      WHEN dormancy_flag AND days_since_last_transaction > 60 THEN 'DORMANCY'
      WHEN declining_balance_flag AND primary_account_balance < 100 THEN 'BALANCE_DECLINE'
      WHEN reduced_activity_flag THEN 'ACTIVITY_REDUCTION'
      WHEN complaint_flag AND open_complaints_count > 0 THEN 'COMPLAINTS'
      WHEN low_engagement_flag THEN 'LOW_ENGAGEMENT'
      WHEN churn_risk_score > 50 THEN 'MULTI_FACTOR'
      ELSE 'NONE'
    END as primary_risk_driver,
    
    -- Build risk drivers JSON
    OBJECT_CONSTRUCT(
      'declining_balance', OBJECT_CONSTRUCT('flag', declining_balance_flag, 'balance', total_relationship_balance),
      'reduced_activity', OBJECT_CONSTRUCT('flag', reduced_activity_flag, 'trend', transaction_trend),
      'low_engagement', OBJECT_CONSTRUCT('flag', low_engagement_flag, 'score', digital_engagement_score),
      'complaints', OBJECT_CONSTRUCT('flag', complaint_flag, 'open_count', open_complaints_count, 'total_12m', complaints_last_12m),
      'dormancy', OBJECT_CONSTRUCT('flag', dormancy_flag, 'days_inactive', days_since_last_transaction)
    )::STRING as risk_drivers_json,
    
    -- Determine recommended intervention
    CASE
      WHEN churn_risk_score > 75 THEN 'URGENT_ESCALATION'
      WHEN churn_risk_score > 50 AND complaint_flag THEN 'RELATIONSHIP_CALL'
      WHEN churn_risk_score > 50 THEN 'RETENTION_OFFER'
      WHEN churn_risk_score > 25 AND low_engagement_flag THEN 'DIGITAL_ENGAGEMENT'
      WHEN churn_risk_score > 25 THEN 'BRANCH_MEETING'
      ELSE 'NO_ACTION'
    END as recommended_intervention,
    
    -- Set intervention priority
    CASE
      WHEN churn_risk_score > 75 THEN 1
      WHEN churn_risk_score > 50 THEN 2
      WHEN churn_risk_score > 25 THEN 3
      ELSE 4
    END as intervention_priority,
    
    CURRENT_TIMESTAMP() as score_calculated_at,
    CURRENT_DATE() as data_as_of_date,
    '1.0.0' as model_version
    
  FROM risk_flags
)

SELECT * FROM final
