-- ============================================================================
-- MASKING POLICIES: Generated from Data Contract
-- ============================================================================
-- Generated by: dbt Code Generator (03b_dbt_generator_app.py)
-- Source: Data Contract (02_design/churn_risk_data_contract.yaml)
--
-- Contract: retail-customer-churn-risk v1.0.0
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_BANKING_DB;
USE SCHEMA DATA_PRODUCTS;

-- ============================================================================
-- MASKING POLICY: CUSTOMER_NAME_MASK
-- ============================================================================
-- Applies to: customer_name
-- Description: Mask customer name for unauthorized users
-- Behavior: Show first character + asterisks for unauthorized roles
-- Example: "John Smith" becomes "J****"
-- ============================================================================

CREATE OR REPLACE MASKING POLICY customer_name_mask
AS (val STRING)
RETURNS STRING ->
    CASE
        -- Authorized roles can see full value
        WHEN CURRENT_ROLE() IN (
            'RETENTION_ANALYST', 
            'BRANCH_MANAGER', 
            'CUSTOMER_ANALYTICS', 
            'COMPLIANCE_OFFICER', 
            'DATA_SCIENCE_TEAM'
        ) THEN val
        -- All other roles see masked value
        ELSE CONCAT(LEFT(val, 1), '****')
    END;

COMMENT ON MASKING POLICY customer_name_mask IS
'Mask customer name for unauthorized users. Contract: retail-customer-churn-risk v1.0.0';

-- ============================================================================
-- APPLY MASKING POLICY TO TABLE
-- ============================================================================

ALTER TABLE IF EXISTS RETAIL_BANKING_DB.DATA_PRODUCTS.RETAIL_CUSTOMER_CHURN_RISK
    MODIFY COLUMN customer_name
    SET MASKING POLICY customer_name_mask;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Test 1: Verify policy is applied
SELECT 
    policy_name,
    policy_kind,
    ref_database_name,
    ref_schema_name,
    ref_entity_name,
    ref_column_name
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    POLICY_NAME => 'RETAIL_BANKING_DB.DATA_PRODUCTS.CUSTOMER_NAME_MASK'
));

-- Test 2: Check masking behavior (run as different roles)
-- As authorized role:
-- USE ROLE RETENTION_ANALYST;
-- SELECT customer_id, customer_name FROM RETAIL_CUSTOMER_CHURN_RISK LIMIT 5;
-- Expected: Full names visible (e.g., "John Smith")

-- As unauthorized role:
-- USE ROLE PUBLIC;
-- SELECT customer_id, customer_name FROM RETAIL_CUSTOMER_CHURN_RISK LIMIT 5;
-- Expected: Names show as "J****", "M****", etc.
