name: 'retail_churn_risk'
version: '1.0.0'
config-version: 2

profile: 'snowflake_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  database: 'RETAIL_BANKING_DB'
  schema: 'DATA_PRODUCTS'
  raw_schema: 'RAW'

models:
  retail_churn_risk:
    +materialized: table
    +tags: ['churn', 'risk', 'retention']
