-- ============================================================================
-- MASKING POLICIES: Generated from Data Contract
-- ============================================================================
-- This file is auto-generated by the dbt Code Generator (03b) based on
-- the masking_policies section of the data contract.
--
-- Contract: retail-customer-churn-risk v1.0.0
-- Generated: [timestamp]
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_BANKING_DB;
USE SCHEMA DATA_PRODUCTS;

-- ============================================================================
-- MASKING POLICY: CUSTOMER_NAME_MASK
-- ============================================================================
-- Source: Contract masking_policies.CUSTOMER_NAME_MASK
-- 
-- Description: Mask customer name for unauthorized users
-- Behavior: 
--   - Authorized roles see full value
--   - Other roles see first character + asterisks (e.g., "John Smith" → "J****")
-- ============================================================================

CREATE OR REPLACE MASKING POLICY customer_name_mask
AS (val STRING) 
RETURNS STRING ->
    CASE 
        -- Authorized roles can see the full customer name
        WHEN CURRENT_ROLE() IN (
            'RETENTION_ANALYST',
            'BRANCH_MANAGER', 
            'CUSTOMER_ANALYTICS',
            'COMPLIANCE_OFFICER',
            'DATA_SCIENCE_TEAM'
        ) THEN val
        
        -- All other roles see masked value: first character + ****
        ELSE CONCAT(LEFT(val, 1), '****')
    END;

-- Add comment for documentation
COMMENT ON MASKING POLICY customer_name_mask IS 
'Masks customer name showing only first initial for unauthorized roles. 
Authorized roles: retention_analyst, branch_manager, customer_analytics, compliance_officer, data_science_team.
Contract: retail-customer-churn-risk v1.0.0';

-- ============================================================================
-- APPLY MASKING POLICY TO TABLE
-- ============================================================================
-- Apply the masking policy to the customer_name column

ALTER TABLE IF EXISTS RETAIL_BANKING_DB.DATA_PRODUCTS.RETAIL_CUSTOMER_CHURN_RISK
    MODIFY COLUMN customer_name 
    SET MASKING POLICY customer_name_mask;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Test 1: Verify policy is applied
SELECT 
    policy_name,
    policy_kind,
    ref_database_name,
    ref_schema_name,
    ref_entity_name,
    ref_column_name
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    POLICY_NAME => 'RETAIL_BANKING_DB.DATA_PRODUCTS.CUSTOMER_NAME_MASK'
));

-- Test 2: Check masking behavior (run as different roles)
-- As authorized role:
-- USE ROLE RETENTION_ANALYST;
-- SELECT customer_id, customer_name FROM RETAIL_CUSTOMER_CHURN_RISK LIMIT 5;
-- Expected: Full names visible

-- As unauthorized role:
-- USE ROLE PUBLIC;
-- SELECT customer_id, customer_name FROM RETAIL_CUSTOMER_CHURN_RISK LIMIT 5;
-- Expected: Names show as "J****", "M****", etc.

-- ============================================================================
-- ADDITIONAL MASKING POLICIES (Template for future use)
-- ============================================================================
-- The following are templates for common FSI masking patterns.
-- Uncomment and customize as needed.

/*
-- Email masking: show domain only
CREATE OR REPLACE MASKING POLICY email_mask
AS (val STRING) 
RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() IN ('RETENTION_ANALYST', 'COMPLIANCE_OFFICER') THEN val
        ELSE CONCAT('****@', SPLIT_PART(val, '@', 2))
    END;

-- Phone masking: show last 4 digits only  
CREATE OR REPLACE MASKING POLICY phone_mask
AS (val STRING) 
RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() IN ('RETENTION_ANALYST', 'COMPLIANCE_OFFICER') THEN val
        ELSE CONCAT('****-****-', RIGHT(REGEXP_REPLACE(val, '[^0-9]', ''), 4))
    END;

-- Account number masking: show last 4 digits only
CREATE OR REPLACE MASKING POLICY account_number_mask
AS (val STRING) 
RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() IN ('RETENTION_ANALYST', 'COMPLIANCE_OFFICER') THEN val
        ELSE CONCAT('****', RIGHT(val, 4))
    END;
*/

-- ============================================================================
-- END OF GENERATED MASKING POLICIES
-- ============================================================================

