# ============================================================================
# SOURCES
# ============================================================================
version: 2
sources:
- name: raw
  database: RETAIL_BANKING_DB
  schema: RAW
  tables:
  - name: customers
    description: Core customer demographics and profile
  - name: accounts
    description: Customer accounts and products
  - name: transactions
    description: Account transaction history
  - name: digital_engagement
    description: Mobile app and online banking activity
  - name: complaints
    description: Customer complaints and service issues


# ============================================================================
# MODELS
# ============================================================================
version: 2
models:
- name: retail_customer_churn_risk
  description: "A governed, daily-refreshed data product providing unified churn risk\
    \ \nscores for retail banking customers. Combines behavioral signals, \ntransactional\
    \ patterns, and engagement data to produce explainable \nrisk scores that power\
    \ retention campaigns and branch interventions.\n"
  config:
    materialized: table
    tags:
    - data_product
    - generated_from_contract
  meta:
    owner: sarah.mitchell@bank.com
    sla: Data updated daily by 6 AM UTC
    contract_version: 1.0.0
  columns:
  - name: customer_id
    description: Unique identifier for the retail customer
    tests:
    - unique
    - not_null
    tags:
    - identifier
    - customer
    - business_key
  - name: customer_name
    description: Full name of the customer
    tests:
    - not_null
    tags:
    - pii
    - customer
    - name
  - name: customer_segment
    description: Customer segment classification
    tests:
    - not_null
    tags:
    - customer
    - segment
    - classification
  - name: region
    description: Geographic region of the customer
    tests:
    - not_null
    tags:
    - customer
    - geography
  - name: relationship_tenure_months
    description: Number of months since customer onboarding
    tests:
    - not_null
    tags:
    - customer
    - tenure
    - relationship
  - name: total_products_held
    description: Count of active products held by customer
    tests:
    - not_null
    tags:
    - customer
    - products
    - relationship
  - name: primary_account_balance
    description: Balance of primary current account in GBP
    tests:
    - not_null
    tags:
    - financial
    - balance
    - account
  - name: total_relationship_balance
    description: Sum of all account balances in GBP
    tests:
    - not_null
    tags:
    - financial
    - balance
    - relationship
  - name: avg_monthly_transactions_3m
    description: Average monthly transaction count over last 3 months
    tests:
    - not_null
    tags:
    - behavioral
    - transactions
    - activity
  - name: transaction_trend
    description: Transaction volume trend direction
    tests:
    - not_null
    tags:
    - behavioral
    - trend
    - indicator
  - name: balance_trend
    description: Account balance trend direction
    tests:
    - not_null
    tags:
    - behavioral
    - trend
    - indicator
  - name: days_since_last_transaction
    description: Days since the last account transaction
    tests:
    - not_null
    tags:
    - behavioral
    - dormancy
    - activity
  - name: mobile_app_active
    description: Whether customer has used mobile app in last 30 days
    tests:
    - not_null
    tags:
    - digital
    - engagement
    - mobile
  - name: login_count_30d
    description: Number of digital banking logins in last 30 days
    tests:
    - not_null
    tags:
    - digital
    - engagement
    - activity
  - name: digital_engagement_score
    description: Composite digital engagement score (0-100)
    tests:
    - not_null
    tags:
    - digital
    - engagement
    - score
  - name: open_complaints_count
    description: Number of currently open complaints
    tests:
    - not_null
    tags:
    - service
    - complaints
    - risk_factor
  - name: complaints_last_12m
    description: Total complaints filed in last 12 months
    tests:
    - not_null
    tags:
    - service
    - complaints
    - history
  - name: has_unresolved_complaint
    description: Flag indicating unresolved complaint exists
    tests:
    - not_null
    tags:
    - service
    - complaints
    - risk_flag
  - name: churn_risk_score
    description: Calculated churn risk score (0-100, higher = more risk)
    tests:
    - not_null
    tags:
    - output
    - risk_score
    - churn
    - primary
  - name: risk_tier
    description: Risk categorization based on score thresholds
    tests:
    - not_null
    tags:
    - output
    - risk_tier
    - churn
    - classification
  - name: declining_balance_flag
    description: Significant balance decline detected
    tests:
    - not_null
    tags:
    - risk_driver
    - explainability
    - balance
  - name: reduced_activity_flag
    description: Reduced transaction activity detected
    tests:
    - not_null
    tags:
    - risk_driver
    - explainability
    - activity
  - name: low_engagement_flag
    description: Low digital engagement detected
    tests:
    - not_null
    tags:
    - risk_driver
    - explainability
    - engagement
  - name: complaint_flag
    description: Recent or unresolved complaint exists
    tests:
    - not_null
    tags:
    - risk_driver
    - explainability
    - complaints
  - name: dormancy_flag
    description: Account showing dormancy signals
    tests:
    - not_null
    tags:
    - risk_driver
    - explainability
    - dormancy
  - name: primary_risk_driver
    description: The most significant factor contributing to churn risk
    tests:
    - not_null
    tags:
    - output
    - explainability
    - primary_driver
  - name: risk_drivers_json
    description: JSON object of all contributing risk factors with details
    tests:
    - not_null
    tags:
    - output
    - explainability
    - drivers_detail
  - name: recommended_intervention
    description: Suggested retention intervention based on risk profile
    tests:
    - not_null
    tags:
    - output
    - recommendation
    - action
  - name: intervention_priority
    description: Priority ranking for intervention (1=highest)
    tests:
    - not_null
    tags:
    - output
    - priority
    - action
  - name: score_calculated_at
    description: Timestamp when churn score was calculated
    tests:
    - not_null
    tags:
    - metadata
    - audit
    - timestamp
  - name: data_as_of_date
    description: Business date of the source data
    tests:
    - not_null
    tags:
    - metadata
    - audit
    - date
  - name: model_version
    description: Version of the churn risk model used
    tests:
    - not_null
    tags:
    - metadata
    - model
    - version
