retail_churn_risk:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <YOUR_SNOWFLAKE_ACCOUNT>
      user: <YOUR_USER>
      warehouse: COMPUTE_WH
      database: RETAIL_BANKING_DB
      schema: DATA_PRODUCTS
      role: ACCOUNTADMIN
