# ============================================================================
# SOURCES
# ============================================================================
# Source definitions for the upstream tables used by the churn risk model
# ============================================================================
version: 2
sources:
  - name: raw
    database: RETAIL_BANKING_DB
    schema: RAW
    description: Raw source tables for retail banking data
    tables:
      - name: customers
        description: Core customer demographics and profile
        columns:
          - name: customer_id
            description: Unique identifier for the customer
          - name: customer_name
            description: Full name of the customer
          - name: customer_segment
            description: Customer segment classification
          - name: region
            description: Geographic region
          - name: onboarding_date
            description: Date customer was onboarded
          - name: kyc_status
            description: KYC verification status
      - name: accounts
        description: Customer accounts and products
        columns:
          - name: account_id
            description: Unique account identifier
          - name: customer_id
            description: Customer who owns the account
          - name: account_type
            description: Type of account (CURRENT_ACCOUNT, SAVINGS, etc.)
          - name: current_balance
            description: Current balance in GBP
          - name: account_status
            description: Account status (ACTIVE, CLOSED, etc.)
      - name: transactions
        description: Account transaction history
        columns:
          - name: txn_id
            description: Unique transaction identifier
          - name: account_id
            description: Account the transaction belongs to
          - name: txn_date
            description: Date of transaction
          - name: amount
            description: Transaction amount
          - name: channel
            description: Channel used for transaction
      - name: digital_engagement
        description: Mobile app and online banking activity
        columns:
          - name: customer_id
            description: Customer identifier
          - name: login_count_30d
            description: Login count in last 30 days
          - name: mobile_app_active
            description: Whether mobile app was used recently
          - name: online_banking_active
            description: Whether online banking was used recently
          - name: features_used_count
            description: Number of features used
          - name: measurement_date
            description: Date of measurement
      - name: complaints
        description: Customer complaints and service issues
        columns:
          - name: complaint_id
            description: Unique complaint identifier
          - name: customer_id
            description: Customer who filed the complaint
          - name: status
            description: Complaint status (OPEN, CLOSED, etc.)
          - name: severity
            description: Complaint severity level
          - name: complaint_date
            description: Date complaint was filed


# ============================================================================
# MODELS
# ============================================================================
# Model definition for the retail customer churn risk data product
# ============================================================================
---
version: 2
models:
  - name: retail_customer_churn_risk
    description: |
      A governed, daily-refreshed data product providing unified churn risk 
      scores for retail banking customers. Combines behavioral signals, 
      transactional patterns, and engagement data to produce explainable 
      risk scores that power retention campaigns and branch interventions.
    config:
      materialized: table
      tags:
        - data_product
        - generated_from_contract
        - churn_risk
    meta:
      owner: alex.morgan@bank.com
      team: Retail Customer Analytics
      sla: Data updated daily by 6 AM UTC
      contract_version: '1.0.0'
      data_classification: confidential
    columns:
      # Customer Identifiers
      - name: customer_id
        description: Unique identifier for the retail customer
        tests:
          - unique
          - not_null
        tags:
          - identifier
          - customer
          - business_key
      - name: customer_name
        description: Full name of the customer
        tests:
          - not_null
        tags:
          - pii
          - customer
          - name
      - name: customer_segment
        description: Customer segment classification
        tests:
          - not_null
          - accepted_values:
              values: ['MASS_MARKET', 'MASS_AFFLUENT', 'AFFLUENT', 'HIGH_NET_WORTH']
        tags:
          - customer
          - segment
          - classification
      - name: region
        description: Geographic region of the customer
        tests:
          - not_null
        tags:
          - customer
          - geography

      # Relationship Attributes
      - name: relationship_tenure_months
        description: Number of months since customer onboarding
        tests:
          - not_null
        tags:
          - customer
          - tenure
          - relationship
      - name: total_products_held
        description: Count of active products held by customer
        tests:
          - not_null
        tags:
          - customer
          - products
          - relationship
      - name: primary_account_balance
        description: Balance of primary current account in GBP
        tests:
          - not_null
        tags:
          - financial
          - balance
          - account
      - name: total_relationship_balance
        description: Sum of all account balances in GBP
        tests:
          - not_null
        tags:
          - financial
          - balance
          - relationship

      # Behavioral Signals
      - name: avg_monthly_transactions_3m
        description: Average monthly transaction count over last 3 months
        tests:
          - not_null
        tags:
          - behavioral
          - transactions
          - activity
      - name: transaction_trend
        description: Transaction volume trend direction
        tests:
          - not_null
          - accepted_values:
              values: ['INCREASING', 'STABLE', 'DECLINING', 'SEVERELY_DECLINING']
        tags:
          - behavioral
          - trend
          - indicator
      - name: balance_trend
        description: Account balance trend direction
        tests:
          - not_null
          - accepted_values:
              values: ['INCREASING', 'STABLE', 'DECLINING', 'SEVERELY_DECLINING']
        tags:
          - behavioral
          - trend
          - indicator
      - name: days_since_last_transaction
        description: Days since the last account transaction
        tests:
          - not_null
        tags:
          - behavioral
          - dormancy
          - activity

      # Digital Engagement Signals
      - name: mobile_app_active
        description: Whether customer has used mobile app in last 30 days
        tests:
          - not_null
        tags:
          - digital
          - engagement
          - mobile
      - name: login_count_30d
        description: Number of digital banking logins in last 30 days
        tests:
          - not_null
        tags:
          - digital
          - engagement
          - activity
      - name: digital_engagement_score
        description: Composite digital engagement score (0-100)
        tests:
          - not_null
        tags:
          - digital
          - engagement
          - score

      # Complaint & Service Signals
      - name: open_complaints_count
        description: Number of currently open complaints
        tests:
          - not_null
        tags:
          - service
          - complaints
          - risk_factor
      - name: complaints_last_12m
        description: Total complaints filed in last 12 months
        tests:
          - not_null
        tags:
          - service
          - complaints
          - history
      - name: has_unresolved_complaint
        description: Flag indicating unresolved complaint exists
        tests:
          - not_null
        tags:
          - service
          - complaints
          - risk_flag

      # Churn Risk Outputs
      - name: churn_risk_score
        description: Calculated churn risk score (0-100, higher = more risk)
        tests:
          - not_null
        tags:
          - output
          - risk_score
          - churn
          - primary
      - name: risk_tier
        description: Risk categorization based on score thresholds
        tests:
          - not_null
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
        tags:
          - output
          - risk_tier
          - churn
          - classification

      # Risk Driver Flags
      - name: declining_balance_flag
        description: Significant balance decline detected
        tests:
          - not_null
        tags:
          - risk_driver
          - explainability
          - balance
      - name: reduced_activity_flag
        description: Reduced transaction activity detected
        tests:
          - not_null
        tags:
          - risk_driver
          - explainability
          - activity
      - name: low_engagement_flag
        description: Low digital engagement detected
        tests:
          - not_null
        tags:
          - risk_driver
          - explainability
          - engagement
      - name: complaint_flag
        description: Recent or unresolved complaint exists
        tests:
          - not_null
        tags:
          - risk_driver
          - explainability
          - complaints
      - name: dormancy_flag
        description: Account showing dormancy signals
        tests:
          - not_null
        tags:
          - risk_driver
          - explainability
          - dormancy

      # Explainability
      - name: primary_risk_driver
        description: The most significant factor contributing to churn risk
        tests:
          - not_null
          - accepted_values:
              values: ['BALANCE_DECLINE', 'ACTIVITY_REDUCTION', 'LOW_ENGAGEMENT', 'COMPLAINTS', 'DORMANCY', 'MULTI_FACTOR', 'NONE']
        tags:
          - output
          - explainability
          - primary_driver
      - name: risk_drivers_json
        description: JSON object of all contributing risk factors with details
        tests:
          - not_null
        tags:
          - output
          - explainability
          - drivers_detail

      # Recommended Actions
      - name: recommended_intervention
        description: Suggested retention intervention based on risk profile
        tests:
          - not_null
          - accepted_values:
              values: ['NO_ACTION', 'DIGITAL_ENGAGEMENT', 'RELATIONSHIP_CALL', 'BRANCH_MEETING', 'RETENTION_OFFER', 'URGENT_ESCALATION']
        tags:
          - output
          - recommendation
          - action
      - name: intervention_priority
        description: Priority ranking for intervention (1=highest)
        tests:
          - not_null
        tags:
          - output
          - priority
          - action

      # Metadata & Audit
      - name: score_calculated_at
        description: Timestamp when churn score was calculated
        tests:
          - not_null
        tags:
          - metadata
          - audit
          - timestamp
      - name: data_as_of_date
        description: Business date of the source data
        tests:
          - not_null
        tags:
          - metadata
          - audit
          - date
      - name: model_version
        description: Version of the churn risk model used
        tests:
          - not_null
        tags:
          - metadata
          - model
          - version
